# Generated by Django 2.2.10 on 2020-10-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_category_todos_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priorities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
